#################################################################
####   Automation of lights in the morning on work days     #####
#################################################################

- alias: ' Go to work weekday'
  trigger:
    - platform: time
      at: '07:10:00'

  condition:
    - condition: state
      entity_id: device_tracker.pi_nexus5x
      state: not_home
    - condition: input_boolean.work_day
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_off
      entity_id:
        - group.kitchen_lights_card
        - light.vardagsrumsfonster_hoger
        - light.vardagsrumsfonster_vanster
    - service: switch.turn_off
      entity_id:
        - switch.hallenvagg
        - switch.koketfonster
        - switch.kokhornskap
        - switch.koksbanken
