###################################
####  Sunset landscap lights on
###################################

- alias: 'Sunset landscap lights on'
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'


  action:
    - service: light.turn_on
      entity_id:
        - light.baksidan
        - light.garage_porten
        - light.lampabron
        - light.vardagsrumsfonster_hoger
        - light.vardagsrumsfonster_vanster
        - light.tradfri_bulb_e14_ws_opal_400lm_2
    - service: switch.turn_on
      entity_id:
        - switch.hallenvagg
        - switch.koketfonster
        - switch.kontoretfonster
    - delay: '00:{{ (range(1, 20)|random|int) }}:00'
    - service: script.speech_engine
      data:
        call_dark_outside: 1
        call_garage_check: 1
        call_window_check: 1
