#################################################################
####   Automation of lights in the morning on work days     #####
#################################################################

- alias: ' Good Morning'
  trigger:
    - platform: time
      at: '05:24:00'

  condition:
    - condition: state
      entity_id: device_tracker.pi_nexus5x
      state: home
    - condition: input_boolean.work_day
      state: 'on'
    - condition: sun
      state: 'below_horizon'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      entity_id:
        - group.kitchen_lights_card
        - light.vardagsrumsfonster_hoger
        - light.vardagsrumsfonster_vanster
    - service: switch.turn_on
      entity_id:
        - switch.hallenvagg
        - switch.koketfonster
        - switch.kokhornskap
        - switch.koksbanken
