- alias: 'Set my status home'
  trigger:
    - platform: state
      entity_id: group.family
      to: 'home'

  condition:
    - condition: state
      entity_id: group.family
      state: 'home'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.bjorn_status
        option: "Home"
    - service: notify.bjorn
      data_template:
        title: 'Bjorn is Home'
        message: 'Bjorn is now {{ states.input_select.bjorn_status.state }}'
