- alias: 'Goodmorning rutin weekends'
  trigger:
    - platform: time
      at: '07:15:00'

  condition:
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: input_boolean.work_mode
      state: 'on'
    - condition: time
      weekday:
        - sat
        - sun

  action:
    - service: script.turn_on
      entity_id: script.goodmorning
