- alias: 'Timed 0525'
  trigger:
    - platform: time
      at: '05:25:00'


  condition:
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: input_boolean.work_mode
      state: 'on'
    - condition: sun
      before: sunrise
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.sovrummsfonster
          - light.vardagsrumsfonster_hoger
          - light.vardagsrumsfonster_vanster
          - light.koksfonster_vanster
          - light.koksfonster_hoger
          - light.taklampa_hallen
          - light.labwindow
    - service: switch.turn_on
      data:
        entity_id:
          - switch.koksbanken
          - switch.kokhornskap
